### ISSUE TITLE
Can't change a status.active message on an action

### ISSUE THREAD

**Issue by auria** [juju-solutions/layer-status#9]
After setting an "active" message via hooks, I later tried to set a different "active" message via an action and it did nothing. I could not see any logging on the unit log.

However using the following did work, 
```python
#!/usr/local/sbin/charm-env python3
from charmhelpers.core.hookenv import status_set
status_set('active', 'Ready')
```

FYI, layer is included without changing the default hookenv patch (which is true).

Is there any problem changing messages when the working state does not change? Or am I missing something else?

**Comment by johnsca** [comment]
This happens because there is a finalization step to sort out conflicts in status due by message severity which isn't being setup or invoked.  This is really only needed if the main reactive loop is running and dispatching to handlers.

I need to make it work correctly even if the finalization is not setup.

**Comment by tonid7** [comment]
The layer.status._initialize() gives an attribute error when the reactive is initiated from my action:

> 2019-05-29 16:35:20 ERROR juju-log Hook error:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-camera-ueemu-13/.venv/lib/python3.5/site-packages/charms/reactive/__init__.py", line 70,
 in main
    bus.discover()
  File "/var/lib/juju/agents/unit-camera-ueemu-13/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 424, in
discover
    _register_handlers_from_file(search_path, filepath)
  File "/var/lib/juju/agents/unit-camera-ueemu-13/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 454, in
_register_handlers_from_file
    _load_module(root, filepath)
  File "/var/lib/juju/agents/unit-camera-ueemu-13/.venv/lib/python3.5/site-packages/charms/reactive/bus.py", line 442, in
_load_module
    return importlib.import_module(package + module)
  File "/var/lib/juju/agents/unit-camera-ueemu-13/.venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/lib/juju/agents/unit-camera-ueemu-13/charm/reactive/status.py", line 4, in <module>
    layer.status._initialize()
AttributeError: module 'charms.layer' has no attribute 'status'

If I import status and initialize it the problem is not there. Is it an issue or am i missing something?

`from charms.layer import status`
`status._initialize()`

Thanks!

**Comment by johnsca** [comment]
Does your `layer.yaml` file have `layer:status` in its `includes` list?

**Comment by tonid7** [comment]
Not explicitly, as my layer.yaml includes layer-apt which includes layer-status. But the built charm's layer.yaml does have it

**Comment by tonid7** [comment]
after build the layer.yaml looks like this:
```
"includes":
- "layer:options"
- "layer:basic"
- "layer:status"
- "layer:apt"
- "interface:lte_uu_emu"
- "interface:nrpe-external-master"
- "layer:debug"
- "layer:nagios"
- "interface:dockerhost"
- "interface:sdn-plugin"
- "layer:docker"
- "layer:docker_orchestration"
- "interface:ip_port_exchange"
- "layer:ueemu"
- "layer:camera"
"options":
  "apt":
    "packages":
    - ...
    "version_package": ""
    "full_version": !!bool "false"
    "keys": []
  "status":
    "patch-hookenv": !!bool "false"
  "ueemu": {}
  "basic":
    "packages": []
    "use_venv": !!bool "true"
    "python_packages": []
    "include_system_packages": !!bool "true"
  "debug": {}
  "camera-ueemu": {}
  "camera": {}
  "docker":
    "skip-install": !!bool "false"
  "nagios": {}
  "docker_orchestration": {}
"repo": "https://..."
"exclude":
- "LAYER_README.md"
- "tests/10-deploy.py"
- "tests/tests.yaml"
"is": "camera-ueemu"
```

**Comment by jamesbeedy** [comment]
I've been hitting the `AttributeError: module 'charms.layer' has no attribute 'status'` error too, in caas charms.

When this happens, I notice that my charm doesn't look like a caas charm, I'm finding non-caas charm layer stuff in my hooks. For example:
```
$ cat build/builds/slurmctld-k8s/hooks/start 
```
```python
#!/usr/bin/env python3

# Load modules from $JUJU_CHARM_DIR/lib
import sys
sys.path.insert(0, 'lib')

from charms.layer import caas_base
caas_base.init_config_states()
caas_base.import_layer_libs()


# This will load and run the appropriate @hook and other decorated
# handlers from $JUJU_CHARM_DIR/reactive, $JUJU_CHARM_DIR/hooks/reactive,
# and $JUJU_CHARM_DIR/hooks/relations.
#
# See https://jujucharms.com/docs/stable/authors-charm-building
# for more information on this pattern.
from charms.reactive import main
main()
```

**Comment by jamesbeedy** [comment]
I think I just found out why this was happening for me; I had `layer-leadership` included in my charm (which includes [layer-basic](https://github.com/stub42/layer-leadership/blob/master/layer.yaml#L17)). If you are building caas charms (it doesn't look like you are), you have to make sure that no child layers include layer-basic.

https://github.com/stub42/layer-leadership/pull/1
